name: DeployGihubPage

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
          node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN  }}
      - run: |
          npm install
          npm run build
          touch ./build/.nojekyll
          touch ./build/static/js/.nojekyll
          touch ./build/static/css/.nojekyll
          git config --global user.email "github@example.com"
          git config --global user.name "git workflows"
          git add build/ -f
          git commit -m "Deploy gh-pages"          
          #git subtree push --prefix build origin gh-pages
          git subtree split --prefix build -b gh-pages
          git push -f origin gh-pages:gh-pages
          git branch -D gh-pages
